name: Ec2-deployement


on: 
  push:
    branches:
      - main

jobs:
  deploy:
     runs-on: ubuntu-latest

     steps:
     - name: code checkout
       uses: action-checkout@v2

     - name: install dependencies
       run: |
         sudo apt update
         sudo apt install nginx -y

     - name: build and test
       run: |
         # testing scripts

     - name: deployement steps
       uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
           whoami
